server:
  port: 8761

spring:
  application:
    name: eureka-registry

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defulatZone: http://localhost:8761/eureka