server:
  port: 6050
 
spring:
  application:
    name: author-client

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defultZone: http://localhost:8761/eureka
      
      
      
